# Generated by Django 4.2.9 on 2024-03-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_petowner_zipcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="petowner",
            name="user_type",
            field=models.CharField(default="pet-owner", max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="petsitter",
            name="user_type",
            field=models.CharField(default="pet-sitter", max_length=15, null=True),
        ),
    ]
