# Generated by Django 4.2.9 on 2024-03-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_petowner_user_type_petsitter_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petowner",
            name="user_type",
            field=models.CharField(
                blank=True, default="pet-owner", max_length=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="petsitter",
            name="user_type",
            field=models.CharField(
                blank=True, default="pet-sitter", max_length=15, null=True
            ),
        ),
    ]
