FROM python:3.10 as builder

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY requirements.txt requirements.txt ./

# Add trusted hosts to work on corpo machines
ENV PIP_TRUSTED_HOST="pypi.org files.pythonhosted.org pypi.python.org raw.githubusercontent.com github.com gitlab.com"
RUN pip install -U pip setuptools==57.5.0
RUN pip config --site set global.trusted-host "pypi.org files.pythonhosted.org pypi.python.org raw.githubusercontent.com github.com gitlab.com"
RUN pip install -r requirements.txt

FROM python:3.10 AS runner
#COPY --from=hashicorp/terraform:0.15.5 /bin/terraform /usr/local/bin/terraform
COPY --from=builder /opt/venv /opt/venv

RUN apt-get update && apt-get install -y \
        git \
        libpangocairo-1.0-0 \
        libzbar0 \
        poppler-utils \
    && rm -rf /var/lib/apt/lists/*

ADD . /app/
WORKDIR /app

ENV VIRTUAL_ENV=/opt/venv
RUN python -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

EXPOSE ${PORT}

CMD python manage.py runserver