# Generated by Django 4.2.9 on 2024-02-25 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=50)),
                ("request", models.TextField(blank=True)),
                ("sent_date", models.DateField(auto_now_add=True)),
                ("accepted", models.BooleanField(default=False)),
                ("accepted_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-sent_date"],
            },
        ),
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pet_owner_bookings", models.PositiveIntegerField(default=0)),
                (
                    "pet_owner_expenditure",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("pet_sitter_bookings", models.PositiveIntegerField(default=0)),
                (
                    "pet_sitter_earnings",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
