# Generated by Django 4.2.9 on 2024-03-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_appointment_appointment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="cancelled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appointment",
            name="cancelled_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
