# Generated by Django 4.2.9 on 2024-03-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_appointment_cancelled_appointment_cancelled_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="pet_name",
            field=models.CharField(default="asdasd", max_length=50),
            preserve_default=False,
        ),
    ]
